FROM node:18.16.0-alpine
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "yarn.lock", "./"]

RUN yarn install --freeze-lockfile --production

COPY . .

RUN yarn add global @nestjs/cli
RUN yarn build
